### PR TITLE
Create intave-03-pterodactyl.md

### PR DESCRIPTION
**Pull request by mrpf-me**
Docs page on using Intave with Pterodactyl (Docker).

### CODE REVIEW

**Review by mrpf-me — COMMENTED** [review]
incorrect path for root directory fixed.

**Comment by lennoxlotl** [comment]
Thanks for this contribution!

**Comment by mrpf-me** [comment]
Is it possible to link the guide to the Docs page? @lennoxlotl 
This would help new customers.
https://github.com/intave/documentation/blob/master/guides/README.md

**Comment by Janmm14** [comment]
> Is it possible to link the guide to the Docs page? @lennoxlotl This would help new customers. https://github.com/intave/documentation/blob/master/guides/README.md

The whole page doesnt want to build rn for richy. Its not a problem of not mentioned in readme.

**Comment by mrpf-me** [comment]
> > Is it possible to link the guide to the Docs page? @lennoxlotl This would help new customers. https://github.com/intave/documentation/blob/master/guides/README.md
> 
> The whole page doesnt want to build rn for richy. Its not a problem of not mentioned in readme.

I see, until this is fixed I've added the guide to my wiki, hope that's ok.
https://discord.com/channels/393821443688890368/468529965021921290/1183141226833260584

**Pull request merged**
